export const ADD_DATA = "ADD_DATA";
export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const PRODUCT_SELECTED = "PRODUCT_SELECTED";
export const PRODUCT_UNCHECKED = "PRODUCT_UNCHECKED";
export const ADD_ADDRESS = "ADD_ADDRESS";